import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Providers from "./providers";
import Navbar from "@/components/Navbar";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

import { Noto_Serif } from "next/font/google";

const notoSerif = Noto_Serif({
  subsets: ["latin"],
  weight: ["400", "700"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "VibeDiary",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="light">
      <head>
            <style>{`
            @font-face {
               font-family: "Distrela";
               src: url("https://files.jcink.net/uploads2/leaptesting/Ekahermawan___Distrela_Regular.otf");
            }

            @font-face {
               font-family: "Chronicle";
               src: url("https://files.jcink.net/uploads2/leaptesting/Chronicle_Deck_Bold.otf");
            }

            :root {
               --title: "Distrela", serif;
               --title2: "Chronicle", serif;
               --body: "Noto Serif", serif;
            }

            body {
               font-family: var(--body);
            }
            `}</style>
      </head>
      <body
        className={notoSerif.className}
      >

        <div className="fixed inset-0 -z-10 overflow-hidden">
          <div className="absolute w-72 h-72 bg-pink-300 opacity-30 rounded-full blur-3xl animate-pulse-slow top-[-80px] left-[60px]" />
          <div className="absolute w-72 h-72 bg-purple-300 opacity-30 rounded-full blur-3xl animate-pulse-slower bottom-[-80px] right-[60px]" />
        </div>

        <Providers>
          <Navbar />
          {children}
        </Providers>
      </body>
    </html>
  );
}
